Resources:
  DynamoDBLambdaFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: org.ipo.fetch.db.QueryDynamoDBHandler::handleRequest
      Runtime: java17
      CodeUri: target/fetch-data-1.0-SNAPSHOT.jar
      MemorySize: 512
      Timeout: 60
      Environment:
        Variables:
          TABLE_NAME: "LambdaTable"  # Ensure this is set correctly
      Policies:
        - AWSLambdaBasicExecutionRole
        - Version: '2012-10-17'
          Statement:
            - Effect: 'Allow'
              Action:
                - 'dynamodb:GetItem'
              Resource: 'arn:aws:dynamodb:ap-south-1:123456789012:table/LambdaTable'
