Resources:
  DataScrapperLambdaFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: org.ipo.web.lambda.WebScrapperLambda::handleRequest
      Runtime: java21
      CodeUri: target/ipo-data-scrapper-1.0-SNAPSHOT.jar
      MemorySize: 128
      Timeout: 120
      Environment:
        Variables:
          TABLE_NAME: "IPOData"  # Ensure this is set correctly
      Policies:
        - AWSLambdaBasicExecutionRole
        - Version: '2012-10-17'
          Statement:
            - Effect: 'Allow'
              Action:
                - 'dynamodb:GetItem'
              Resource: 'arn:aws:dynamodb:ap-south-1:123456789012:table/IPOData'

  UserTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: IPOData
      AttributeDefinitions:
        - AttributeName: ipoId
          AttributeType: s
      KeySchema:
        - AttributeName: ipoId
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2
